Update U-Boot to 2024.07
USB-related options (e.g. UMS) in U-Boot 2024.04 could not be
built (on the sunxi target) due to an: "undefined reference to
dm_usb_gadget_handle_interrupts". This function is correctly
provided by `drivers/usb/musb-new/musb_uboot.c` in 2024.07.